EXP:
  MODEL_NAME: "relativit"
  EXP_ID: "rel3d_relativit"

DATALOADER:
  datapath: "./data/rel3d/c_0.9_c_0.1.json"
  batch_size: 64
  load_img: True
  crop: False
  norm_data: True
  data_aug_shift: True
  data_aug_color: True

TRAIN:
  num_epochs: 200
  learning_rate: 1e-5
  l2: 1e-4
  layer_decay: 0.75
  optimizer: adamw
  scheduler: cosine
  warmup: 5

MODEL:
  VISION_TRANSFORMER:
    pretrained: "./data/pretrained_checkpoints/ibot_vit_base_patch16.pth"
    readnet_d_hidden: 512
  RELATIVIT:
    prompt_emb_pool: "max-in-roi"
    use_attn_mask: True