EXP:
  MODEL_NAME: "cross-attn-vit"
  EXP_ID: "spatialsense_CrossAttnViT"

DATALOADER:
  dataset_name: "spatialsense"
  datapath: "./data/spatial_sense/annots_spatialsenseplus.json"
  load_img: True
  crop: False
  norm_data: True
  data_aug_shift: True
  data_aug_color: True
  predicate_dim: 9
  object_dim: 3679
  batch_size: 64

TRAIN:
  num_epochs: 100
  learning_rate: 1e-5
  l2: 1e-3
  optimizer: adamw
  layer_decay: 0.75
  scheduler: cosine
  warmup: 5

MODEL:
  VISION_TRANSFORMER:
    pretrained: "./data/pretrained_checkpoints/ibot_vit_base_patch16.pth"
  CROSSATTNVIT:
    decoder_depth: 1
    decoder_drop_rate: 0.1
    emb_pool: "max-in-roi"

